-- Q1. 저자 별 카테고리 별 매출액 집계하기 답 
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, 
    SUM(s.SALES* b.PRICE) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;

-- Q2. 언어 별 개발자 분류하기 답
WITH SKILL_CODES AS (
    SELECT BIT_OR(CODE) AS SKILL_CODE 
    FROM SKILLCODES 
    GROUP BY CATEGORY 
    HAVING CATEGORY = 'Front End'
), SKILL_GRADE AS (
    SELECT
        CASE
            WHEN d.SKILL_CODE & s.SKILL_CODE 
                AND d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
                THEN 'A'
            WHEN d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') 
                THEN 'B'
            WHEN d.SKILL_CODE & s.SKILL_CODE 
                THEN 'C'
            ELSE NULL
        END AS GRADE, d.ID, d.EMAIL
    FROM DEVELOPERS d, SKILL_CODES s
)
SELECT GRADE, ID, EMAIL
FROM SKILL_GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;