-- Q1. 서울에 위치한 식당 목록 출력하기 
SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS,
    ROUND(AVG(rr.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO ri
JOIN REST_REVIEW rr ON ri.REST_ID = rr.REST_ID
WHERE REGEXP_LIKE(ri.ADDRESS, '^서울')
GROUP BY ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS
ORDER BY SCORE DESC, ri.FAVORITES DESC;


-- Q2. 부모의 형질을 모두 가지는 대장균 출력하기 
SELECT e.ID, e.GENOTYPE, d.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA e
JOIN ECOLI_DATA d 
    ON e.PARENT_ID = d.ID
WHERE (e.GENOTYPE | d.GENOTYPE) = e.GENOTYPE
ORDER BY e.ID;
